language: php

php:
  - 7.1

before_script:
 - travis_retry composer self-update
 - travis_retry composer install --no-interaction --prefer-source --dev

script:
 - vendor/bin/phpunit --coverage-clover=clover.xml
 - mkdir -p build/logs

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
  - php vendor/bin/codacycoverage clover clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
