language: php

php:
  - 5.6
  - 7.0

before_script: composer install -n

script:
 - bin/phpunit --coverage-clover=clover.xml
 - mkdir -p build/logs

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
  - wget https://github.com/codacy/php-codacy-coverage/raw/master/bin/phar/codacycoverage.phar
  - php codacycoverage.phar clover clover.xml
