language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script: composer install -n

script:
 - bin/phpunit -c app --coverage-clover=coverage.clover
 - mkdir -p build/logs
 - cp coverage.clover clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - wget https://github.com/codacy/php-codacy-coverage/raw/master/bin/phar/codacycoverage.phar
  - php codacycoverage.phar clover clover.xml
