app:
    resource: "@AppBundle/Controller/"
    type:     annotation

wallpaper_redirect:
    path: /wallpaper/{name}
    defaults: { _controller: AppBundle:Redirecting:wallpaperRedirect }
    requirements:
        url: .*/$
    methods: [GET]

# must be last
app.remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
